language: php
php:
 - 5.6

# This helps builds go quicker on Travis since it enables caching of dependencies
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

services: 
 - mysql

install:
 - composer self-update
 - composer install
 - mysql -e 'create database elgg;'
 - echo "USE mysql; UPDATE user SET password=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;" | mysql -u root
 - mkdir "${HOME}/elgg_data/"
 - php -f ./install/cli/travis_installer.php
 
script:
 - ./vendor/bin/phpunit
 - php -f ./engine/tests/suite.php
